name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            cmake_args: ''
            built: 'build/voxxum'
            artifact_name: 'voxxum-linux'

          - name: linux (ARM)
            os: ubuntu-24.04-arm
            cmake_args: ''
            built: 'build/voxxum'
            artifact_name: 'voxxum-linux-arm'

          - name: windows
            os: windows-latest
            cmake_args: '-A x64'
            built: 'build/Release/voxxum.exe'
            artifact_name: 'voxxum-windows.exe'

          - name: windows (arm)
            os: windows-latest
            cmake_args: '-A ARM64'
            built: 'build/Release/voxxum.exe'
            artifact_name: 'voxxum-windows-arm.exe'

          - name: mac (arm)
            os: macos-14
            cmake_args: '-DCMAKE_OSX_ARCHITECTURES=arm64'
            built: 'build/voxxum'
            artifact_name: 'voxxum-macos'

          - name: mac
            os: macos-14
            cmake_args: '-DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13'
            built: 'build/voxxum'
            artifact_name: 'voxxum-macos-x64'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Install tool
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxkbcommon-dev libgl1-mesa-dev libdbus-1-dev
      - name: cmake
        uses: jwlawson/actions-setup-cmake@v2.2.0
        with:
          cmake-version: '4.4.x'

      - name: config cmake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmake_args }}

      - name: Build
        run: cmake --build build --config Release --parallel

      - shell: bash
        run: mv ${{ matrix.built }} ${{ matrix.artifact_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}